version: "3.9"

services:
  ejabberd:
    build: ./ejabberd/
    ports:
      - "5222:5222"
      - "5280:5280"
    environment:
      - "EJABBERD_ADMIN_PASSWORD=${EJABBERD_ADMIN_PASSWORD:-admin}"
  client:
    build: ./client/
    depends_on:
      - ejabberd
    environment:
      - "SERVER_DOMAIN=ejabberd"
